import { Campaign } from "./type.campaign.js";
import { StatUpgradeOption } from "./type.campaign.js";
import { GameMode } from "../game/type.game.js";

export const flattenedSpherionCampaign: Campaign = {
  name: "The Flattened Spherion",
  slug: "flattened-spherion",
  description: "Master the art of collectables in this challenging campaign featuring dynamic spawning power-ups.",
  games: [
    {
      name: "Game 1: First Collectable",
      mode: {
        name: "Flattened Spherion 1",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 0,
        numGremlakShips: 3,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
        spawnFoodChance: 5,
        spawnShieldChance: 0,
        spawnIceChance: 0,
      },
      intro: {
        type: "text",
        text: "Welcome to the Flattened Spherion campaign. Collect the orange food circles to restore your health.",
      },
      victory: {
        type: "text",
        text: "You survived with the power of food! More challenges await.",
      },
      defeat: {
        type: "text",
        text: "The spherion proved too flat for you this time. Try again.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health],
        numSelections: 1,
      },
    },
    {
      name: "Game 2: Shield Up",
      mode: {
        name: "Flattened Spherion 2",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 0,
        numGremlakShips: 5,
        numGravity: 0,
        numHunter: 2,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
        spawnFoodChance: 3,
        spawnShieldChance: 5,
        spawnIceChance: 0,
      },
      intro: {
        type: "text",
        text: "Now with shields! Blue circles make you immune to damage for a short time.",
      },
      victory: {
        type: "text",
        text: "Shielded success! The spherion flattens before you.",
      },
      defeat: {
        type: "text",
        text: "Even with shields, the challenge was too great.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed],
        numSelections: 1,
      },
    },
    {
      name: "Game 3: Ice Age",
      mode: {
        name: "Flattened Spherion 3",
        worldWidth: 1100,
        worldHeight: 1100,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 0,
        numGremlakShips: 4,
        numGravity: 1,
        numHunter: 1,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
        spawnFoodChance: 4,
        spawnShieldChance: 3,
        spawnIceChance: 5,
      },
      intro: {
        type: "text",
        text: "The spherion grows colder. White ice circles freeze enemies in place, giving you time to maneuver.",
      },
      victory: {
        type: "text",
        text: "Frozen foes couldn't stop you! The ice age is yours to command.",
      },
      defeat: {
        type: "text",
        text: "The cold proved too much. Warm up with another try.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed],
        numSelections: 1,
      },
    },
    {
      name: "Game 4: Gravity Feast",
      mode: {
        name: "Flattened Spherion 4",
        worldWidth: 1100,
        worldHeight: 1100,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 0,
        numGremlakShips: 3,
        numGravity: 3,
        numHunter: 0,
        numBlockade: 2,
        numVoid: 0,
        numGhost: 0,
        spawnFoodChance: 6,
        spawnShieldChance: 2,
        spawnIceChance: 2,
      },
      intro: {
        type: "text",
        text: "Gravity wells pull you off course, but food circles abound. Master the pull to feast safely.",
      },
      victory: {
        type: "text",
        text: "You feasted under gravity's gaze! The spherion's pull strengthens.",
      },
      defeat: {
        type: "text",
        text: "Gravity dragged you down before you could eat. Try again.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 5: Hunter's Shield",
      mode: {
        name: "Flattened Spherion 5",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 0,
        numGremlakShips: 2,
        numGravity: 1,
        numHunter: 4,
        numBlockade: 1,
        numVoid: 0,
        numGhost: 0,
        spawnFoodChance: 3,
        spawnShieldChance: 7,
        spawnIceChance: 1,
      },
      intro: {
        type: "text",
        text: "Hunters stalk relentlessly. Shields are your best defense—use them wisely to survive the chase.",
      },
      victory: {
        type: "text",
        text: "Shielded from the hunters! Your defenses grow stronger.",
      },
      defeat: {
        type: "text",
        text: "The hunters pierced your shield. Fortify and return.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 6: Frozen Maze",
      mode: {
        name: "Flattened Spherion 6",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 0,
        numGremlakShips: 3,
        numGravity: 0,
        numHunter: 2,
        numBlockade: 6,
        numVoid: 0,
        numGhost: 0,
        spawnFoodChance: 4,
        spawnShieldChance: 4,
        spawnIceChance: 4,
      },
      intro: {
        type: "text",
        text: "Blockades form a maze. Freeze enemies to navigate safely and collect your power-ups.",
      },
      victory: {
        type: "text",
        text: "You navigated the frozen maze! The spherion's labyrinths deepen.",
      },
      defeat: {
        type: "text",
        text: "Lost in the maze without freezing aid. Find your way back.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 7: Void Feast",
      mode: {
        name: "Flattened Spherion 7",
        worldWidth: 1300,
        worldHeight: 1300,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 0,
        numGremlakShips: 4,
        numGravity: 2,
        numHunter: 1,
        numBlockade: 0,
        numVoid: 3,
        numGhost: 0,
        spawnFoodChance: 8,
        spawnShieldChance: 3,
        spawnIceChance: 2,
      },
      intro: {
        type: "text",
        text: "Voids drain your health from afar. Feast on food to counter their pull and survive.",
      },
      victory: {
        type: "text",
        text: "You feasted despite the voids! The darkness encroaches further.",
      },
      defeat: {
        type: "text",
        text: "The voids starved you out. Nourish yourself next time.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 8: Ghost Shield",
      mode: {
        name: "Flattened Spherion 8",
        worldWidth: 1300,
        worldHeight: 1300,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 0,
        numGremlakShips: 2,
        numGravity: 1,
        numHunter: 3,
        numBlockade: 2,
        numVoid: 1,
        numGhost: 3,
        spawnFoodChance: 3,
        spawnShieldChance: 8,
        spawnIceChance: 3,
      },
      intro: {
        type: "text",
        text: "Ghosts appear unpredictably. Shields protect you from their sudden attacks—stay vigilant.",
      },
      victory: {
        type: "text",
        text: "Shielded from the spectral threat! The ghosts grow bolder.",
      },
      defeat: {
        type: "text",
        text: "The ghosts phased through your defenses. Shield up and try again.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 9: Ice Storm",
      mode: {
        name: "Flattened Spherion 9",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 0,
        numGremlakShips: 5,
        numGravity: 3,
        numHunter: 2,
        numBlockade: 1,
        numVoid: 2,
        numGhost: 1,
        spawnFoodChance: 5,
        spawnShieldChance: 5,
        spawnIceChance: 7,
      },
      intro: {
        type: "text",
        text: "An ice storm rages. Freeze the chaos to create safe zones and collect power-ups amidst the flurry.",
      },
      victory: {
        type: "text",
        text: "You weathered the ice storm! The spherion's fury intensifies.",
      },
      defeat: {
        type: "text",
        text: "Frozen in the storm. Melt the ice with strategy.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 10: Gravity Gauntlet",
      mode: {
        name: "Flattened Spherion 10",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 4,
        numGreenCircles: 0,
        numGremlakShips: 4,
        numGravity: 5,
        numHunter: 3,
        numBlockade: 3,
        numVoid: 1,
        numGhost: 2,
        spawnFoodChance: 6,
        spawnShieldChance: 4,
        spawnIceChance: 4,
      },
      intro: {
        type: "text",
        text: "Navigate the gravity gauntlet. Use food for health, shields for protection, and ice to halt the pull.",
      },
      victory: {
        type: "text",
        text: "You conquered the gravity gauntlet! The spherion tests your limits.",
      },
      defeat: {
        type: "text",
        text: "Gravity's gauntlet was too tight. Loosen up with power-ups.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 11: Hunter's Ice",
      mode: {
        name: "Flattened Spherion 11",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 4,
        numGreenCircles: 0,
        numGremlakShips: 3,
        numGravity: 2,
        numHunter: 6,
        numBlockade: 2,
        numVoid: 0,
        numGhost: 1,
        spawnFoodChance: 4,
        spawnShieldChance: 3,
        spawnIceChance: 8,
      },
      intro: {
        type: "text",
        text: "Hunters swarm in packs. Freeze them to break their pursuit and survive the horde.",
      },
      victory: {
        type: "text",
        text: "Frozen hunters couldn't catch you! The packs grow larger.",
      },
      defeat: {
        type: "text",
        text: "The hunter pack overwhelmed you. Freeze and flee.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 12: Void Maze",
      mode: {
        name: "Flattened Spherion 12",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 4,
        numGreenCircles: 0,
        numGremlakShips: 4,
        numGravity: 1,
        numHunter: 2,
        numBlockade: 8,
        numVoid: 4,
        numGhost: 2,
        spawnFoodChance: 7,
        spawnShieldChance: 6,
        spawnIceChance: 3,
      },
      intro: {
        type: "text",
        text: "A maze of voids and blockades. Feast and shield to navigate the dark corridors safely.",
      },
      victory: {
        type: "text",
        text: "You escaped the void maze! The spherion's darkness spreads.",
      },
      defeat: {
        type: "text",
        text: "Trapped in the void maze. Light your path with power-ups.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 13: Ghost Storm",
      mode: {
        name: "Flattened Spherion 13",
        worldWidth: 1600,
        worldHeight: 1600,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 5,
        numGreenCircles: 0,
        numGremlakShips: 5,
        numGravity: 3,
        numHunter: 3,
        numBlockade: 1,
        numVoid: 2,
        numGhost: 6,
        spawnFoodChance: 5,
        spawnShieldChance: 9,
        spawnIceChance: 5,
      },
      intro: {
        type: "text",
        text: "A storm of ghosts haunts the arena. Shields are your only defense against their ethereal assault.",
      },
      victory: {
        type: "text",
        text: "Shielded from the ghost storm! The spirits grow restless.",
      },
      defeat: {
        type: "text",
        text: "The ghosts phased through. Fortify your shields.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 14: Ice Gauntlet",
      mode: {
        name: "Flattened Spherion 14",
        worldWidth: 1600,
        worldHeight: 1600,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 5,
        numGreenCircles: 0,
        numGremlakShips: 6,
        numGravity: 4,
        numHunter: 4,
        numBlockade: 4,
        numVoid: 3,
        numGhost: 3,
        spawnFoodChance: 6,
        spawnShieldChance: 4,
        spawnIceChance: 9,
      },
      intro: {
        type: "text",
        text: "The ultimate ice gauntlet. Freeze everything in your path to master the frozen chaos.",
      },
      victory: {
        type: "text",
        text: "You froze the gauntlet! The spherion's core challenges await.",
      },
      defeat: {
        type: "text",
        text: "Frozen solid. Thaw with better strategy.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 15: Feast of Shadows",
      mode: {
        name: "Flattened Spherion 15",
        worldWidth: 1700,
        worldHeight: 1700,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 5,
        numGreenCircles: 0,
        numGremlakShips: 4,
        numGravity: 2,
        numHunter: 5,
        numBlockade: 3,
        numVoid: 5,
        numGhost: 4,
        spawnFoodChance: 10,
        spawnShieldChance: 5,
        spawnIceChance: 4,
      },
      intro: {
        type: "text",
        text: "A feast amidst shadows. Voids and ghosts surround you—eat to survive the darkness.",
      },
      victory: {
        type: "text",
        text: "You feasted in the shadows! The spherion's heart darkens.",
      },
      defeat: {
        type: "text",
        text: "Starved by shadows. Feast on victory next time.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 16: Shield Citadel",
      mode: {
        name: "Flattened Spherion 16",
        worldWidth: 1700,
        worldHeight: 1700,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 6,
        numGreenCircles: 0,
        numGremlakShips: 5,
        numGravity: 3,
        numHunter: 4,
        numBlockade: 7,
        numVoid: 2,
        numGhost: 3,
        spawnFoodChance: 4,
        spawnShieldChance: 12,
        spawnIceChance: 3,
      },
      intro: {
        type: "text",
        text: "The shield citadel stands. Blockades and enemies guard it—shield yourself to breach the walls.",
      },
      victory: {
        type: "text",
        text: "Citadel breached! Your shields hold strong.",
      },
      defeat: {
        type: "text",
        text: "The citadel repelled you. Reinforce your shields.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 17: Frozen Abyss",
      mode: {
        name: "Flattened Spherion 17",
        worldWidth: 1800,
        worldHeight: 1800,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 6,
        numGreenCircles: 0,
        numGremlakShips: 6,
        numGravity: 4,
        numHunter: 5,
        numBlockade: 2,
        numVoid: 6,
        numGhost: 5,
        spawnFoodChance: 7,
        spawnShieldChance: 6,
        spawnIceChance: 10,
      },
      intro: {
        type: "text",
        text: "The abyss freezes over. Combine ice with food and shields to survive the deep void.",
      },
      victory: {
        type: "text",
        text: "You froze the abyss! The depths yield to your power.",
      },
      defeat: {
        type: "text",
        text: "Plunged into the frozen abyss. Climb out with collectables.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 18: Gravity Nexus",
      mode: {
        name: "Flattened Spherion 18",
        worldWidth: 1800,
        worldHeight: 1800,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 6,
        numGreenCircles: 0,
        numGremlakShips: 7,
        numGravity: 6,
        numHunter: 6,
        numBlockade: 5,
        numVoid: 4,
        numGhost: 4,
        spawnFoodChance: 8,
        spawnShieldChance: 7,
        spawnIceChance: 6,
      },
      intro: {
        type: "text",
        text: "The gravity nexus pulls all. Master every collectable to escape its crushing force.",
      },
      victory: {
        type: "text",
        text: "Nexus conquered! Gravity bends to your will.",
      },
      defeat: {
        type: "text",
        text: "Crushed by the nexus. Pull yourself free.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 19: Hunter's Citadel",
      mode: {
        name: "Flattened Spherion 19",
        worldWidth: 1900,
        worldHeight: 1900,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 7,
        numGreenCircles: 0,
        numGremlakShips: 5,
        numGravity: 3,
        numHunter: 8,
        numBlockade: 6,
        numVoid: 3,
        numGhost: 3,
        spawnFoodChance: 5,
        spawnShieldChance: 10,
        spawnIceChance: 7,
      },
      intro: {
        type: "text",
        text: "Hunters guard the citadel. Freeze and shield to storm their fortress.",
      },
      victory: {
        type: "text",
        text: "Citadel stormed! The hunters flee before you.",
      },
      defeat: {
        type: "text",
        text: "Repelled by the citadel. Breach with ice and shields.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 20: Void Citadel",
      mode: {
        name: "Flattened Spherion 20",
        worldWidth: 1900,
        worldHeight: 1900,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 7,
        numGreenCircles: 0,
        numGremlakShips: 6,
        numGravity: 4,
        numHunter: 4,
        numBlockade: 8,
        numVoid: 7,
        numGhost: 6,
        spawnFoodChance: 9,
        spawnShieldChance: 8,
        spawnIceChance: 5,
      },
      intro: {
        type: "text",
        text: "The void citadel looms. Feast and shield to survive its draining halls.",
      },
      victory: {
        type: "text",
        text: "Void citadel fallen! The darkness retreats.",
      },
      defeat: {
        type: "text",
        text: "Drained by the citadel. Nourish your strength.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 21: Ghost Nexus",
      mode: {
        name: "Flattened Spherion 21",
        worldWidth: 2000,
        worldHeight: 2000,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 7,
        numGreenCircles: 0,
        numGremlakShips: 7,
        numGravity: 5,
        numHunter: 5,
        numBlockade: 4,
        numVoid: 5,
        numGhost: 8,
        spawnFoodChance: 6,
        spawnShieldChance: 11,
        spawnIceChance: 8,
      },
      intro: {
        type: "text",
        text: "The ghost nexus haunts. Shields and ice are your weapons against the spectral horde.",
      },
      victory: {
        type: "text",
        text: "Nexus exorcised! The ghosts dissipate.",
      },
      defeat: {
        type: "text",
        text: "Haunted by the nexus. Banish with power-ups.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 22: Ice Citadel",
      mode: {
        name: "Flattened Spherion 22",
        worldWidth: 2000,
        worldHeight: 2000,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 8,
        numGreenCircles: 0,
        numGremlakShips: 8,
        numGravity: 6,
        numHunter: 6,
        numBlockade: 9,
        numVoid: 6,
        numGhost: 5,
        spawnFoodChance: 7,
        spawnShieldChance: 6,
        spawnIceChance: 12,
      },
      intro: {
        type: "text",
        text: "The ice citadel freezes time. Master freezing to conquer its eternal walls.",
      },
      victory: {
        type: "text",
        text: "Citadel thawed! Your freezing power prevails.",
      },
      defeat: {
        type: "text",
        text: "Frozen in the citadel. Break free with strategy.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 23: Feast Nexus",
      mode: {
        name: "Flattened Spherion 23",
        worldWidth: 2100,
        worldHeight: 2100,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 8,
        numGreenCircles: 0,
        numGremlakShips: 6,
        numGravity: 4,
        numHunter: 7,
        numBlockade: 5,
        numVoid: 8,
        numGhost: 7,
        spawnFoodChance: 13,
        spawnShieldChance: 7,
        spawnIceChance: 6,
      },
      intro: {
        type: "text",
        text: "The feast nexus calls. Abundant food awaits, but voids and ghosts guard it hungrily.",
      },
      victory: {
        type: "text",
        text: "Nexus feasted upon! Your hunger conquers all.",
      },
      defeat: {
        type: "text",
        text: "Starved at the nexus. Devour victory.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 24: Shield Nexus",
      mode: {
        name: "Flattened Spherion 24",
        worldWidth: 2100,
        worldHeight: 2100,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 8,
        numGreenCircles: 0,
        numGremlakShips: 9,
        numGravity: 7,
        numHunter: 8,
        numBlockade: 7,
        numVoid: 7,
        numGhost: 8,
        spawnFoodChance: 8,
        spawnShieldChance: 15,
        spawnIceChance: 9,
      },
      intro: {
        type: "text",
        text: "The shield nexus protects. Arm yourself with shields to face the ultimate convergence.",
      },
      victory: {
        type: "text",
        text: "Nexus shielded! Your defenses are impenetrable.",
      },
      defeat: {
        type: "text",
        text: "Breached by the nexus. Shield yourself better.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 25: The Flattened Core",
      mode: {
        name: "Flattened Spherion 25",
        worldWidth: 2200,
        worldHeight: 2200,
        numCircles: 0,
        mode: GameMode.enum.Survival,
        timeLimit: 0,
        health: 10,
        numGreenCircles: 0,
        numGremlakShips: 10,
        numGravity: 8,
        numHunter: 9,
        numBlockade: 10,
        numVoid: 9,
        numGhost: 9,
        spawnFoodChance: 10,
        spawnShieldChance: 10,
        spawnIceChance: 10,
      },
      intro: {
        type: "text",
        text: "The flattened core awaits. Master all collectables in the ultimate test of survival.",
      },
      victory: {
        type: "text",
        text: "The spherion is flattened! You are the master of collectables and survival!",
      },
      defeat: {
        type: "text",
        text: "The core remains unflattened. One more push to mastery.",
      },
    },
  ],
};
