import { Campaign } from "./type.campaign.js";
import { StatUpgradeOption } from "./type.campaign.js";
import { GameMode } from "../game/type.game.js";

export const circleManAndTheMightyMinions: Campaign = {
  name: "Circle Man and the Mighty Minions",
  slug: "circle-man-and-the-mighty-minions",
  description:
    "A series of 10 increasingly difficult race games. Master speed and agility against every circle type, including ghosts and voids.",
  games: [
    {
      name: "Game 1: The Sprint",
      mode: {
        name: "Minions 1",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 60,
        health: 2,
        numGreenCircles: 3,
        numGremlakShips: 2,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Mighty Minions have challenged you to a race! Collect three green circles in 60 seconds. The bouncers are just the warm-up.",
      },
      victory: {
        type: "text",
        text: "Fast feet! The Minions are surprised. But they have more tricks up their sleeves...",
      },
      defeat: {
        type: "text",
        text: "Too slow for the Minions! Pick up the pace and try again.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 2: Ghost Town",
      mode: {
        name: "Minions 2",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 60,
        health: 2,
        numGreenCircles: 3,
        numGremlakShips: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 3,
      },
      intro: {
        type: "text",
        text: "Ghost circles haunt the arena — invisible most of the time, they appear only when close. They follow you silently. Race fast before they close in!",
      },
      victory: {
        type: "text",
        text: "You outran the ghosts! But the Minions are opening portals to the void...",
      },
      defeat: {
        type: "text",
        text: "The ghosts caught you off guard. Keep your eyes open and your speed up!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 3: Void Runner",
      mode: {
        name: "Minions 3",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 75,
        health: 2,
        numGreenCircles: 4,
        numGremlakShips: 2,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 3,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Void circles now dot the arena — dark pits that drain your health if you stray too close. Plot a careful course through them to collect four green circles.",
      },
      victory: {
        type: "text",
        text: "You danced around the voids! The Minions are bringing out the heavy artillery...",
      },
      defeat: {
        type: "text",
        text: "Swallowed by the void! Give those dark circles a wider berth.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 4: Blockade Blitz",
      mode: {
        name: "Minions 4",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 75,
        health: 2,
        numGreenCircles: 4,
        numGremlakShips: 2,
        numGravity: 1,
        numHunter: 0,
        numBlockade: 6,
        numVoid: 1,
        numGhost: 1,
      },
      intro: {
        type: "text",
        text: "Blockades create a maze while voids and ghosts lurk in the corridors. Race through the labyrinth before time runs out!",
      },
      victory: {
        type: "text",
        text: "You blazed through the blockade maze! The Minions are escalating...",
      },
      defeat: {
        type: "text",
        text: "Lost in the maze! Memorize the layout and find the optimal path.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 5: Gravity Dash",
      mode: {
        name: "Minions 5",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 90,
        health: 3,
        numGreenCircles: 5,
        numGremlakShips: 3,
        numGravity: 3,
        numHunter: 0,
        numBlockade: 3,
        numVoid: 2,
        numGhost: 2,
      },
      intro: {
        type: "text",
        text: "Gravity wells warp your trajectory while ghosts and voids create deadly zones. Use gravity to slingshot yourself to victory! 90 seconds on the clock.",
      },
      victory: {
        type: "text",
        text: "You mastered the gravitational slingshot! The Minions send their hunters...",
      },
      defeat: {
        type: "text",
        text: "Gravity pulled you off course! Learn to use it as an advantage.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 6: Hunter's Chase",
      mode: {
        name: "Minions 6",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 90,
        health: 3,
        numGreenCircles: 5,
        numGremlakShips: 2,
        numGravity: 2,
        numHunter: 3,
        numBlockade: 4,
        numVoid: 1,
        numGhost: 2,
      },
      intro: {
        type: "text",
        text: "Hunters join the race! They'll chase you relentlessly while ghosts stalk from the shadows. Collect five circles with three hunters on your tail.",
      },
      victory: {
        type: "text",
        text: "You outpaced the hunters! The Minions are getting desperate...",
      },
      defeat: {
        type: "text",
        text: "The hunters cornered you! Stay unpredictable and keep moving.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 7: Phantom Gauntlet",
      mode: {
        name: "Minions 7",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 90,
        health: 3,
        numGreenCircles: 6,
        numGremlakShips: 3,
        numGravity: 2,
        numHunter: 2,
        numBlockade: 5,
        numVoid: 2,
        numGhost: 4,
      },
      intro: {
        type: "text",
        text: "Four ghost circles prowl the arena alongside hunters, voids, and blockades. You can barely see them coming. Trust your instincts and race!",
      },
      victory: {
        type: "text",
        text: "The phantoms couldn't stop you! The Minions are preparing their ultimate arena...",
      },
      defeat: {
        type: "text",
        text: "Ambushed by phantoms! Stay aware of all your surroundings.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 8: Void Storm",
      mode: {
        name: "Minions 8",
        worldWidth: 1600,
        worldHeight: 1600,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 100,
        health: 4,
        numGreenCircles: 7,
        numGremlakShips: 4,
        numGravity: 3,
        numHunter: 3,
        numBlockade: 6,
        numVoid: 5,
        numGhost: 3,
      },
      intro: {
        type: "text",
        text: "A storm of voids opens across the arena — five dark singularities alongside hunters, ghosts, and gravity wells. This is the Minions' most treacherous course yet.",
      },
      victory: {
        type: "text",
        text: "You weathered the void storm! Only two challenges remain...",
      },
      defeat: {
        type: "text",
        text: "The void storm was too intense! Chart a path that avoids the densest clusters.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 9: The Crucible",
      mode: {
        name: "Minions 9",
        worldWidth: 1800,
        worldHeight: 1800,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 120,
        health: 4,
        numGreenCircles: 8,
        numGremlakShips: 5,
        numGravity: 4,
        numHunter: 4,
        numBlockade: 8,
        numVoid: 4,
        numGhost: 5,
      },
      intro: {
        type: "text",
        text: "The Minions' crucible — every circle type in massive numbers. Eight collectibles scattered across a vast arena of chaos. You have 120 seconds. Make every one count.",
      },
      victory: {
        type: "text",
        text: "You survived the crucible! One final race remains. The Mighty Minions await your challenge...",
      },
      defeat: {
        type: "text",
        text: "The crucible melted your ambitions. Study each threat and plan your route!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 10: The Grand Championship",
      mode: {
        name: "Minions 10",
        worldWidth: 2000,
        worldHeight: 2000,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 150,
        health: 5,
        numGreenCircles: 10,
        numGremlakShips: 6,
        numGravity: 5,
        numHunter: 5,
        numBlockade: 10,
        numVoid: 5,
        numGhost: 6,
      },
      intro: {
        type: "text",
        text: "The Grand Championship — the Mighty Minions' ultimate course. Ten collectibles guarded by every circle type in staggering numbers. 150 seconds to prove you are the fastest circle in all of Canzeltly!",
      },
      victory: {
        type: "text",
        text: "CHAMPION! You defeated the Mighty Minions and completed every race! You are the undisputed Circle Man, master of speed and agility!",
      },
      defeat: {
        type: "text",
        text: "So close to the championship! The Mighty Minions still reign. Rally your courage and try once more!",
      },
    },
  ],
};
