import { Campaign } from "./type.campaign.js";
import { StatUpgradeOption } from "./type.campaign.js";
import { GameMode } from "../game/type.game.js";

export const revengeOfTheRadialMaster: Campaign = {
  name: "The Revenge of the Radial Master",
  slug: "revenge-of-the-radial-master",
  description:
    "A series of 10 increasingly difficult adventure games. Master every circle type as the Radial Master fights back.",
  games: [
    {
      name: "Game 1: The Awakening",
      mode: {
        name: "Radial 1",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 3,
        numBouncy: 2,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master has returned from exile. His first wave of bouncing minions guards the collectibles. Navigate carefully — this is only the beginning.",
      },
      victory: {
        type: "text",
        text: "You scattered his vanguard! But the Radial Master is already preparing stronger forces...",
      },
      defeat: {
        type: "text",
        text: "The Radial Master's minions proved too much. Regroup and try again!",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 2: Gravitational Shift",
      mode: {
        name: "Radial 2",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 4,
        numBouncy: 2,
        numGravity: 2,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master has enlisted gravity wells — massive circles whose pull bends your path. Fight gravity itself to collect the green circles.",
      },
      victory: {
        type: "text",
        text: "You bent gravity to your will! But the Radial Master summons hunters for the next assault...",
      },
      defeat: {
        type: "text",
        text: "Gravity dragged you down. Try to use the pull to slingshot around obstacles!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 3: The Hunt Begins",
      mode: {
        name: "Radial 3",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 4,
        numBouncy: 2,
        numGravity: 1,
        numHunter: 2,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Hunter circles are now stalking you — they actively seek you out! Stay mobile, collect fast, and never stop moving.",
      },
      victory: {
        type: "text",
        text: "You outran the hunters! The Radial Master is furious and building walls...",
      },
      defeat: {
        type: "text",
        text: "The hunters tracked you down. Keep moving and never let them corner you!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 4: Fortress of Stone",
      mode: {
        name: "Radial 4",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 2,
        numGreenCircles: 5,
        numBouncy: 3,
        numGravity: 1,
        numHunter: 1,
        numBlockade: 8,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master has fortified the arena with blockades. Massive immovable circles litter the world, creating corridors of danger. Find paths through the maze.",
      },
      victory: {
        type: "text",
        text: "You navigated the fortress! But the Radial Master is combining his forces...",
      },
      defeat: {
        type: "text",
        text: "Trapped in the blockade maze! Study the layout and find the gaps.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 5: Mixed Assault",
      mode: {
        name: "Radial 5",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 5,
        numBouncy: 4,
        numGravity: 2,
        numHunter: 2,
        numBlockade: 5,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master throws everything at once — bouncers, gravity wells, hunters, and blockades all share the arena. This is where the weak fall.",
      },
      victory: {
        type: "text",
        text: "You survived the mixed assault! The Radial Master is impressed... and angry.",
      },
      defeat: {
        type: "text",
        text: "Overwhelmed by the combined forces! Focus on one threat at a time.",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 6: Gravity Storm",
      mode: {
        name: "Radial 6",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 6,
        numBouncy: 3,
        numGravity: 5,
        numHunter: 2,
        numBlockade: 3,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master unleashes a gravity storm — five gravity wells warp the entire arena. Every movement is a struggle against unseen forces.",
      },
      victory: {
        type: "text",
        text: "You rode the gravity waves like a master navigator! The arena grows wider...",
      },
      defeat: {
        type: "text",
        text: "The gravity storm tore you apart. Use gravity to accelerate, not resist it!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 1,
      },
    },
    {
      name: "Game 7: Hunter's Paradise",
      mode: {
        name: "Radial 7",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 6,
        numBouncy: 2,
        numGravity: 2,
        numHunter: 5,
        numBlockade: 4,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Five hunters stalk the arena! The Radial Master's deadliest servants are relentless — they know where you are and they're coming. Collect fast, or perish.",
      },
      victory: {
        type: "text",
        text: "Five hunters defeated! Your legend grows. But the Radial Master's inner sanctum awaits...",
      },
      defeat: {
        type: "text",
        text: "The hunters overwhelmed you. Split their formation and pick them off!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 8: The Gauntlet",
      mode: {
        name: "Radial 8",
        worldWidth: 1600,
        worldHeight: 1600,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 3,
        numGreenCircles: 7,
        numBouncy: 5,
        numGravity: 3,
        numHunter: 3,
        numBlockade: 10,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master's gauntlet — a massive arena packed with every obstacle. Ten blockades form deadly corridors where bouncers and hunters patrol. Only the worthy pass.",
      },
      victory: {
        type: "text",
        text: "You ran the gauntlet and survived! The Radial Master's throne room is near...",
      },
      defeat: {
        type: "text",
        text: "The gauntlet claimed another challenger. Map your route before charging in!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 9: Radial Rage",
      mode: {
        name: "Radial 9",
        worldWidth: 1800,
        worldHeight: 1800,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 4,
        numGreenCircles: 8,
        numBouncy: 6,
        numGravity: 4,
        numHunter: 4,
        numBlockade: 8,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master is enraged! He hurls everything at you with doubled fury. The arena trembles with bouncing chaos, gravitational storms, and relentless hunters.",
      },
      victory: {
        type: "text",
        text: "The Radial Master staggers! One final battle remains. Prepare yourself for the ultimate confrontation...",
      },
      defeat: {
        type: "text",
        text: "The Radial Master's rage overwhelmed you. Steel yourself and try once more!",
      },
      upgrades: {
        options: [StatUpgradeOption.enum.health, StatUpgradeOption.enum.maxSpeed, StatUpgradeOption.enum.acceleration],
        numSelections: 2,
      },
    },
    {
      name: "Game 10: The Final Confrontation",
      mode: {
        name: "Radial 10",
        worldWidth: 2000,
        worldHeight: 2000,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 5,
        numGreenCircles: 10,
        numBouncy: 8,
        numGravity: 5,
        numHunter: 5,
        numBlockade: 12,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "This is it — the Radial Master's throne room. Every type of minion guards the final ten collectibles. Conquer this arena and end the Radial Master's reign forever.",
      },
      victory: {
        type: "text",
        text: "The Radial Master has been defeated! You are the true Circle Champion! But whispers say the Mighty Minions are gathering...",
      },
      defeat: {
        type: "text",
        text: "The Radial Master prevails... for now. You've come too far to give up. Try again!",
      },
    },
  ],
};
