import { Campaign } from "./type.campaign.js";
import { StatUpgradeOption } from "./type.campaign.js";
import { GameMode } from "../game/type.game.js";

export const tutorialCampaign: Campaign = {
  name: "Tutorial",
  slug: "tutorial",
  description: "Learn the basics of Canzeltly through a series of introductory challenges.",
  games: [
    {
      name: "Game 1: First Steps",
      mode: {
        name: "Tutorial 1",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 1,
        numBouncy: 0,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Welcome to Canzeltly, the game of circle survival and adventures. Collect the green circles to win. But watch out, you are the master of gravity in this world...",
      },
      victory: {
        type: "text",
        text: "You mastered the green circle, but you have not mastered gravity! Continue playing to explore this world...",
      },
      defeat: {
        type: "text",
        text: "I don't know how you lost this one, but try again...",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 2: Double Trouble",
      mode: {
        name: "Tutorial 2",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 2,
        numBouncy: 0,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "One circle was easy, right? Now there are two green circles to collect. The world is bigger than you think — explore every corner to find them both.",
      },
      victory: {
        type: "text",
        text: "Two down! You're getting the hang of navigating this strange gravitational landscape. But things are about to get... bouncy.",
      },
      defeat: {
        type: "text",
        text: "Two circles proved too many? Take a breath, regroup, and try again.",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 3: Bouncy Encounter",
      mode: {
        name: "Tutorial 3",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 2,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "A wild bouncing circle has appeared! These restless spheres roam the world, and running into them can be hazardous. Dodge or outmaneuver it while collecting the green circles.",
      },
      victory: {
        type: "text",
        text: "You danced around that bouncy menace like a pro! But the world is building defenses against you...",
      },
      defeat: {
        type: "text",
        text: "That bouncy circle got the better of you. Learn its patterns and try again!",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 4: The Blockade",
      mode: {
        name: "Tutorial 4",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 2,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 5,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The world has erected blockades — immovable circles that stand in your way. Navigate around them carefully while dodging bouncing threats and collecting your prize.",
      },
      victory: {
        type: "text",
        text: "You weaved through the blockades with grace! But the void awaits...",
      },
      defeat: {
        type: "text",
        text: "Trapped between blockades and bouncing circles? Plan your route and try again.",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 5: The Void Beckons",
      mode: {
        name: "Tutorial 5",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Adventure,
        timeLimit: 0,
        health: 1,
        numGreenCircles: 3,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 2,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Void circles have materialized — dark singularities that pull you in and drain your life force. Stay clear of their gravitational pull while collecting three green circles.",
      },
      victory: {
        type: "text",
        text: "You escaped the void's grasp! Now it's time to test your speed...",
      },
      defeat: {
        type: "text",
        text: "The void consumed you. Give those dark circles a wide berth next time!",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 6: Race Against Time",
      mode: {
        name: "Tutorial 6",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 60,
        health: 1,
        numGreenCircles: 3,
        numBouncy: 0,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Time for a race! Collect all three green circles before the clock runs out. Speed and precision are everything. You have 60 seconds — go!",
      },
      victory: {
        type: "text",
        text: "Lightning fast! You beat the clock. But the final test is pure survival...",
      },
      defeat: {
        type: "text",
        text: "Time's up! You weren't fast enough. Optimize your path and try again.",
      },
      upgrades: {
        options: [
          StatUpgradeOption.enum.health,
          StatUpgradeOption.enum.maxSpeed,
          StatUpgradeOption.enum.acceleration,
          StatUpgradeOption.enum.breakSpeed,
        ],
        numSelections: 1,
      },
    },
    {
      name: "Game 7: Final Race",
      mode: {
        name: "Tutorial 7",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: GameMode.enum.Race,
        timeLimit: 60,
        health: 1,
        numGreenCircles: 5,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The final tutorial challenge — a race against time! Collect all five green circles before the clock runs out. Speed and strategy are key. You have 60 seconds — go!",
      },
      victory: {
        type: "text",
        text: "You have now played through the entire tutorial. But the greatest challenge is still ahead...",
      },
      defeat: {
        type: "text",
        text: "Time's up! You have now played through the entire tutorial. But the greatest challenge is still ahead...",
      },
    },
  ],
};
