import { Campaign } from "./type.campaign.js";

export const tutorialCampaign: Campaign = {
  name: "Tutorial",
  slug: "tutorial",
  description: "Learn the basics of Canzeltly through a series of introductory challenges.",
  games: [
    {
      name: "Game 1: First Steps",
      mode: {
        name: "Tutorial 1",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 1,
        numGreenCircles: 1,
        numBouncy: 0,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Welcome to Canzeltly, the game of circle survival and adventures. Collect the green circles to win. But watch out, you are the master of gravity in this world...",
      },
      victory: {
        type: "text",
        text: "You mastered the green circle, but you have not mastered gravity! Continue playing to explore this world...",
      },
      defeat: {
        type: "text",
        text: "I don't know how you lost this one, but try again...",
      },
      upgrades: {
        options: ["health", "maxSpeed", "acceleration"],
        numSelections: 1,
      },
    },
    {
      name: "Game 2: Double Trouble",
      mode: {
        name: "Tutorial 2",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 1,
        numGreenCircles: 2,
        numBouncy: 0,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "One circle was easy, right? Now there are two green circles to collect. The world is bigger than you think — explore every corner to find them both.",
      },
      victory: {
        type: "text",
        text: "Two down! You're getting the hang of navigating this strange gravitational landscape. But things are about to get... bouncy.",
      },
      defeat: {
        type: "text",
        text: "Two circles proved too many? Take a breath, regroup, and try again.",
      },
      upgrades: {
        options: ["health", "maxSpeed", "acceleration"],
        numSelections: 1,
      },
    },
    {
      name: "Game 3: Bouncy Encounter",
      mode: {
        name: "Tutorial 3",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 1,
        numGreenCircles: 2,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "A wild bouncing circle has appeared! These restless spheres roam the world, and running into them can be hazardous. Dodge or outmaneuver it while collecting the green circles.",
      },
      victory: {
        type: "text",
        text: "You danced around that bouncy menace like a pro! But the world is building defenses against you...",
      },
      defeat: {
        type: "text",
        text: "That bouncy circle got the better of you. Learn its patterns and try again!",
      },
      upgrades: {
        options: ["health", "maxSpeed", "acceleration"],
        numSelections: 1,
      },
    },
    {
      name: "Game 4: The Blockade",
      mode: {
        name: "Tutorial 4",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 1,
        numGreenCircles: 2,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 5,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The world has erected blockades — immovable circles that stand in your way. Navigate around them carefully while dodging bouncing threats and collecting your prize.",
      },
      victory: {
        type: "text",
        text: "You weaved through the blockades with grace! But the void awaits...",
      },
      defeat: {
        type: "text",
        text: "Trapped between blockades and bouncing circles? Plan your route and try again.",
      },
      upgrades: {
        options: ["health", "maxSpeed", "acceleration"],
        numSelections: 1,
      },
    },
    {
      name: "Game 5: The Void Beckons",
      mode: {
        name: "Tutorial 5",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 1,
        numGreenCircles: 3,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 2,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Void circles have materialized — dark singularities that pull you in and drain your life force. Stay clear of their gravitational pull while collecting three green circles.",
      },
      victory: {
        type: "text",
        text: "You escaped the void's grasp! Now it's time to test your speed...",
      },
      defeat: {
        type: "text",
        text: "The void consumed you. Give those dark circles a wide berth next time!",
      },
      upgrades: {
        options: ["health", "maxSpeed", "acceleration"],
        numSelections: 1,
      },
    },
    {
      name: "Game 6: Race Against Time",
      mode: {
        name: "Tutorial 6",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Race",
        timeLimit: 60,
        health: 1,
        numGreenCircles: 3,
        numBouncy: 0,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Time for a race! Collect all three green circles before the clock runs out. Speed and precision are everything. You have 60 seconds — go!",
      },
      victory: {
        type: "text",
        text: "Lightning fast! You beat the clock. But the final test is pure survival...",
      },
      defeat: {
        type: "text",
        text: "Time's up! You weren't fast enough. Optimize your path and try again.",
      },
      upgrades: {
        options: ["health", "maxSpeed", "acceleration"],
        numSelections: 1,
      },
    },
    {
      name: "Game 7: Survival Gauntlet",
      mode: {
        name: "Tutorial 7",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 5,
        mode: "Survival",
        timeLimit: 0,
        health: 1,
        numGreenCircles: 0,
        numBouncy: 5,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The final tutorial challenge — pure survival. Five red circles are closing in. Stay alive as long as you can. There is nothing to collect, only danger to avoid.",
      },
      victory: {
        type: "text",
        text: "You have now played through the entire tutorial. But the greatest challenge is still ahead...",
      },
      defeat: {
        type: "text",
        text: "You have now played through the entire tutorial. But the greatest challenge is still ahead...",
      },
    },
  ],
};

export const revengeOfTheRadialMaster: Campaign = {
  name: "The Revenge of the Radial Master",
  slug: "revenge-of-the-radial-master",
  description:
    "A series of 10 increasingly difficult adventure games. Master every circle type as the Radial Master fights back.",
  games: [
    {
      name: "Game 1: The Awakening",
      mode: {
        name: "Radial 1",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 2,
        numGreenCircles: 3,
        numBouncy: 2,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master has returned from exile. His first wave of bouncing minions guards the collectibles. Navigate carefully — this is only the beginning.",
      },
      victory: {
        type: "text",
        text: "You scattered his vanguard! But the Radial Master is already preparing stronger forces...",
      },
      defeat: {
        type: "text",
        text: "The Radial Master's minions proved too much. Regroup and try again!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 2: Gravitational Shift",
      mode: {
        name: "Radial 2",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 2,
        numGreenCircles: 4,
        numBouncy: 2,
        numGravity: 2,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master has enlisted gravity wells — massive circles whose pull bends your path. Fight gravity itself to collect the green circles.",
      },
      victory: {
        type: "text",
        text: "You bent gravity to your will! But the Radial Master summons hunters for the next assault...",
      },
      defeat: {
        type: "text",
        text: "Gravity dragged you down. Try to use the pull to slingshot around obstacles!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 3: The Hunt Begins",
      mode: {
        name: "Radial 3",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 2,
        numGreenCircles: 4,
        numBouncy: 2,
        numGravity: 1,
        numHunter: 2,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Hunter circles are now stalking you — they actively seek you out! Stay mobile, collect fast, and never stop moving.",
      },
      victory: {
        type: "text",
        text: "You outran the hunters! The Radial Master is furious and building walls...",
      },
      defeat: {
        type: "text",
        text: "The hunters tracked you down. Keep moving and never let them corner you!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 4: Fortress of Stone",
      mode: {
        name: "Radial 4",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 2,
        numGreenCircles: 5,
        numBouncy: 3,
        numGravity: 1,
        numHunter: 1,
        numBlockade: 8,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master has fortified the arena with blockades. Massive immovable circles litter the world, creating corridors of danger. Find paths through the maze.",
      },
      victory: {
        type: "text",
        text: "You navigated the fortress! But the Radial Master is combining his forces...",
      },
      defeat: {
        type: "text",
        text: "Trapped in the blockade maze! Study the layout and find the gaps.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 5: Mixed Assault",
      mode: {
        name: "Radial 5",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 3,
        numGreenCircles: 5,
        numBouncy: 4,
        numGravity: 2,
        numHunter: 2,
        numBlockade: 5,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master throws everything at once — bouncers, gravity wells, hunters, and blockades all share the arena. This is where the weak fall.",
      },
      victory: {
        type: "text",
        text: "You survived the mixed assault! The Radial Master is impressed... and angry.",
      },
      defeat: {
        type: "text",
        text: "Overwhelmed by the combined forces! Focus on one threat at a time.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 6: Gravity Storm",
      mode: {
        name: "Radial 6",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 3,
        numGreenCircles: 6,
        numBouncy: 3,
        numGravity: 5,
        numHunter: 2,
        numBlockade: 3,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master unleashes a gravity storm — five gravity wells warp the entire arena. Every movement is a struggle against unseen forces.",
      },
      victory: {
        type: "text",
        text: "You rode the gravity waves like a master navigator! The arena grows wider...",
      },
      defeat: {
        type: "text",
        text: "The gravity storm tore you apart. Use gravity to accelerate, not resist it!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 7: Hunter's Paradise",
      mode: {
        name: "Radial 7",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 3,
        numGreenCircles: 6,
        numBouncy: 2,
        numGravity: 2,
        numHunter: 5,
        numBlockade: 4,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Five hunters stalk the arena! The Radial Master's deadliest servants are relentless — they know where you are and they're coming. Collect fast, or perish.",
      },
      victory: {
        type: "text",
        text: "Five hunters defeated! Your legend grows. But the Radial Master's inner sanctum awaits...",
      },
      defeat: {
        type: "text",
        text: "The hunters overwhelmed you. Split their formation and pick them off!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 8: The Gauntlet",
      mode: {
        name: "Radial 8",
        worldWidth: 1600,
        worldHeight: 1600,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 3,
        numGreenCircles: 7,
        numBouncy: 5,
        numGravity: 3,
        numHunter: 3,
        numBlockade: 10,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master's gauntlet — a massive arena packed with every obstacle. Ten blockades form deadly corridors where bouncers and hunters patrol. Only the worthy pass.",
      },
      victory: {
        type: "text",
        text: "You ran the gauntlet and survived! The Radial Master's throne room is near...",
      },
      defeat: {
        type: "text",
        text: "The gauntlet claimed another challenger. Map your route before charging in!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 9: Radial Rage",
      mode: {
        name: "Radial 9",
        worldWidth: 1800,
        worldHeight: 1800,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 4,
        numGreenCircles: 8,
        numBouncy: 6,
        numGravity: 4,
        numHunter: 4,
        numBlockade: 8,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Radial Master is enraged! He hurls everything at you with doubled fury. The arena trembles with bouncing chaos, gravitational storms, and relentless hunters.",
      },
      victory: {
        type: "text",
        text: "The Radial Master staggers! One final battle remains. Prepare yourself for the ultimate confrontation...",
      },
      defeat: {
        type: "text",
        text: "The Radial Master's rage overwhelmed you. Steel yourself and try once more!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 10: The Final Confrontation",
      mode: {
        name: "Radial 10",
        worldWidth: 2000,
        worldHeight: 2000,
        numCircles: 0,
        mode: "Adventure",
        timeLimit: 0,
        health: 5,
        numGreenCircles: 10,
        numBouncy: 8,
        numGravity: 5,
        numHunter: 5,
        numBlockade: 12,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "This is it — the Radial Master's throne room. Every type of minion guards the final ten collectibles. Conquer this arena and end the Radial Master's reign forever.",
      },
      victory: {
        type: "text",
        text: "The Radial Master has been defeated! You are the true Circle Champion! But whispers say the Mighty Minions are gathering...",
      },
      defeat: {
        type: "text",
        text: "The Radial Master prevails... for now. You've come too far to give up. Try again!",
      },
    },
  ],
};

export const circleManAndTheMightyMinions: Campaign = {
  name: "Circle Man and the Mighty Minions",
  slug: "circle-man-and-the-mighty-minions",
  description:
    "A series of 10 increasingly difficult race games. Master speed and agility against every circle type, including ghosts and voids.",
  games: [
    {
      name: "Game 1: The Sprint",
      mode: {
        name: "Minions 1",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Race",
        timeLimit: 60,
        health: 2,
        numGreenCircles: 3,
        numBouncy: 2,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "The Mighty Minions have challenged you to a race! Collect three green circles in 60 seconds. The bouncers are just the warm-up.",
      },
      victory: {
        type: "text",
        text: "Fast feet! The Minions are surprised. But they have more tricks up their sleeves...",
      },
      defeat: {
        type: "text",
        text: "Too slow for the Minions! Pick up the pace and try again.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 2: Ghost Town",
      mode: {
        name: "Minions 2",
        worldWidth: 1000,
        worldHeight: 1000,
        numCircles: 0,
        mode: "Race",
        timeLimit: 60,
        health: 2,
        numGreenCircles: 3,
        numBouncy: 1,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 0,
        numGhost: 3,
      },
      intro: {
        type: "text",
        text: "Ghost circles haunt the arena — invisible most of the time, they appear only when close. They follow you silently. Race fast before they close in!",
      },
      victory: {
        type: "text",
        text: "You outran the ghosts! But the Minions are opening portals to the void...",
      },
      defeat: {
        type: "text",
        text: "The ghosts caught you off guard. Keep your eyes open and your speed up!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 3: Void Runner",
      mode: {
        name: "Minions 3",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: "Race",
        timeLimit: 75,
        health: 2,
        numGreenCircles: 4,
        numBouncy: 2,
        numGravity: 0,
        numHunter: 0,
        numBlockade: 0,
        numVoid: 3,
        numGhost: 0,
      },
      intro: {
        type: "text",
        text: "Void circles now dot the arena — dark pits that drain your health if you stray too close. Plot a careful course through them to collect four green circles.",
      },
      victory: {
        type: "text",
        text: "You danced around the voids! The Minions are bringing out the heavy artillery...",
      },
      defeat: {
        type: "text",
        text: "Swallowed by the void! Give those dark circles a wider berth.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 4: Blockade Blitz",
      mode: {
        name: "Minions 4",
        worldWidth: 1200,
        worldHeight: 1200,
        numCircles: 0,
        mode: "Race",
        timeLimit: 75,
        health: 2,
        numGreenCircles: 4,
        numBouncy: 2,
        numGravity: 1,
        numHunter: 0,
        numBlockade: 6,
        numVoid: 1,
        numGhost: 1,
      },
      intro: {
        type: "text",
        text: "Blockades create a maze while voids and ghosts lurk in the corridors. Race through the labyrinth before time runs out!",
      },
      victory: {
        type: "text",
        text: "You blazed through the blockade maze! The Minions are escalating...",
      },
      defeat: {
        type: "text",
        text: "Lost in the maze! Memorize the layout and find the optimal path.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 5: Gravity Dash",
      mode: {
        name: "Minions 5",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: "Race",
        timeLimit: 90,
        health: 3,
        numGreenCircles: 5,
        numBouncy: 3,
        numGravity: 3,
        numHunter: 0,
        numBlockade: 3,
        numVoid: 2,
        numGhost: 2,
      },
      intro: {
        type: "text",
        text: "Gravity wells warp your trajectory while ghosts and voids create deadly zones. Use gravity to slingshot yourself to victory! 90 seconds on the clock.",
      },
      victory: {
        type: "text",
        text: "You mastered the gravitational slingshot! The Minions send their hunters...",
      },
      defeat: {
        type: "text",
        text: "Gravity pulled you off course! Learn to use it as an advantage.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 1 },
    },
    {
      name: "Game 6: Hunter's Chase",
      mode: {
        name: "Minions 6",
        worldWidth: 1400,
        worldHeight: 1400,
        numCircles: 0,
        mode: "Race",
        timeLimit: 90,
        health: 3,
        numGreenCircles: 5,
        numBouncy: 2,
        numGravity: 2,
        numHunter: 3,
        numBlockade: 4,
        numVoid: 1,
        numGhost: 2,
      },
      intro: {
        type: "text",
        text: "Hunters join the race! They'll chase you relentlessly while ghosts stalk from the shadows. Collect five circles with three hunters on your tail.",
      },
      victory: {
        type: "text",
        text: "You outpaced the hunters! The Minions are getting desperate...",
      },
      defeat: {
        type: "text",
        text: "The hunters cornered you! Stay unpredictable and keep moving.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 7: Phantom Gauntlet",
      mode: {
        name: "Minions 7",
        worldWidth: 1500,
        worldHeight: 1500,
        numCircles: 0,
        mode: "Race",
        timeLimit: 90,
        health: 3,
        numGreenCircles: 6,
        numBouncy: 3,
        numGravity: 2,
        numHunter: 2,
        numBlockade: 5,
        numVoid: 2,
        numGhost: 4,
      },
      intro: {
        type: "text",
        text: "Four ghost circles prowl the arena alongside hunters, voids, and blockades. You can barely see them coming. Trust your instincts and race!",
      },
      victory: {
        type: "text",
        text: "The phantoms couldn't stop you! The Minions are preparing their ultimate arena...",
      },
      defeat: {
        type: "text",
        text: "Ambushed by phantoms! Stay aware of all your surroundings.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 8: Void Storm",
      mode: {
        name: "Minions 8",
        worldWidth: 1600,
        worldHeight: 1600,
        numCircles: 0,
        mode: "Race",
        timeLimit: 100,
        health: 4,
        numGreenCircles: 7,
        numBouncy: 4,
        numGravity: 3,
        numHunter: 3,
        numBlockade: 6,
        numVoid: 5,
        numGhost: 3,
      },
      intro: {
        type: "text",
        text: "A storm of voids opens across the arena — five dark singularities alongside hunters, ghosts, and gravity wells. This is the Minions' most treacherous course yet.",
      },
      victory: {
        type: "text",
        text: "You weathered the void storm! Only two challenges remain...",
      },
      defeat: {
        type: "text",
        text: "The void storm was too intense! Chart a path that avoids the densest clusters.",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 9: The Crucible",
      mode: {
        name: "Minions 9",
        worldWidth: 1800,
        worldHeight: 1800,
        numCircles: 0,
        mode: "Race",
        timeLimit: 120,
        health: 4,
        numGreenCircles: 8,
        numBouncy: 5,
        numGravity: 4,
        numHunter: 4,
        numBlockade: 8,
        numVoid: 4,
        numGhost: 5,
      },
      intro: {
        type: "text",
        text: "The Minions' crucible — every circle type in massive numbers. Eight collectibles scattered across a vast arena of chaos. You have 120 seconds. Make every one count.",
      },
      victory: {
        type: "text",
        text: "You survived the crucible! One final race remains. The Mighty Minions await your challenge...",
      },
      defeat: {
        type: "text",
        text: "The crucible melted your ambitions. Study each threat and plan your route!",
      },
      upgrades: { options: ["health", "maxSpeed", "acceleration"], numSelections: 2 },
    },
    {
      name: "Game 10: The Grand Championship",
      mode: {
        name: "Minions 10",
        worldWidth: 2000,
        worldHeight: 2000,
        numCircles: 0,
        mode: "Race",
        timeLimit: 150,
        health: 5,
        numGreenCircles: 10,
        numBouncy: 6,
        numGravity: 5,
        numHunter: 5,
        numBlockade: 10,
        numVoid: 5,
        numGhost: 6,
      },
      intro: {
        type: "text",
        text: "The Grand Championship — the Mighty Minions' ultimate course. Ten collectibles guarded by every circle type in staggering numbers. 150 seconds to prove you are the fastest circle in all of Canzeltly!",
      },
      victory: {
        type: "text",
        text: "CHAMPION! You defeated the Mighty Minions and completed every race! You are the undisputed Circle Man, master of speed and agility!",
      },
      defeat: {
        type: "text",
        text: "So close to the championship! The Mighty Minions still reign. Rally your courage and try once more!",
      },
    },
  ],
};

export const allCampaigns: Campaign[] = [tutorialCampaign, revengeOfTheRadialMaster, circleManAndTheMightyMinions];

export function getCampaignBySlug(slug: string): Campaign | undefined {
  return allCampaigns.find((c) => c.slug === slug);
}
